export default function Head() {
  return (
    <>
      <title>Matrix Solutions</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7962958774331843"
     crossorigin="anonymous"></script>
    </>
  )
}
